import 'dart:convert';
sealed class StoryEventPayload { int get payloadVersion; Map<String,Object?> toJson(); }
final class JourneyStartedPayload implements StoryEventPayload { @override final int payloadVersion; final String journeyId; const JourneyStartedPayload(this.journeyId,{this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'journey_id':journeyId}; }
final class GreetingCompletedPayload implements StoryEventPayload { @override final int payloadVersion; final String semanticValue; const GreetingCompletedPayload(this.semanticValue,{this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'semantic_value':semanticValue}; }
final class ItemOrderedPayload implements StoryEventPayload { @override final int payloadVersion; final String itemId; const ItemOrderedPayload(this.itemId,{this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'item_id':itemId}; }
final class StoryNameSetPayload implements StoryEventPayload { @override final int payloadVersion; final String name; const StoryNameSetPayload(this.name,{this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'name':name}; }
final class CharacterLearnedFactPayload implements StoryEventPayload { @override final int payloadVersion; final String characterId; final String factType; final String valueRef; const CharacterLearnedFactPayload({required this.characterId,required this.factType,required this.valueRef,this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'character_id':characterId,'fact_type':factType,'value_ref':valueRef}; }
final class StageCompletedPayload implements StoryEventPayload { @override final int payloadVersion; final String stageId; const StageCompletedPayload(this.stageId,{this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'stage_id':stageId}; }
final class ArtifactUnlockedPayload implements StoryEventPayload { @override final int payloadVersion; final String artifactId; const ArtifactUnlockedPayload(this.artifactId,{this.payloadVersion=1}); @override Map<String,Object?> toJson()=>{'artifact_id':artifactId}; }
abstract final class StoryEventTypes { static const journeyStarted='JOURNEY_STARTED'; static const greetingCompleted='GREETING_COMPLETED'; static const itemOrdered='ITEM_ORDERED'; static const storyNameSet='STORY_NAME_SET'; static const characterLearnedFact='CHARACTER_LEARNED_FACT'; static const stageCompleted='STAGE_COMPLETED'; static const artifactUnlocked='ARTIFACT_UNLOCKED'; }
final class StoryEventPayloadCodec { const StoryEventPayloadCodec(); String encode(StoryEventPayload payload)=>jsonEncode(payload.toJson()); StoryEventPayload decode(String eventType,int version,String raw){ if(version!=1) throw UnsupportedStoryPayloadVersion(eventType,version); final decoded=jsonDecode(raw); if(decoded is! Map<String,dynamic>) throw const FormatException('Story payload must be an object'); return switch(eventType){StoryEventTypes.journeyStarted=>JourneyStartedPayload(decoded['journey_id'] as String),StoryEventTypes.greetingCompleted=>GreetingCompletedPayload(decoded['semantic_value'] as String),StoryEventTypes.itemOrdered=>ItemOrderedPayload(decoded['item_id'] as String),StoryEventTypes.storyNameSet=>StoryNameSetPayload(decoded['name'] as String),StoryEventTypes.characterLearnedFact=>CharacterLearnedFactPayload(characterId:decoded['character_id'] as String,factType:decoded['fact_type'] as String,valueRef:decoded['value_ref'] as String),StoryEventTypes.stageCompleted=>StageCompletedPayload(decoded['stage_id'] as String),StoryEventTypes.artifactUnlocked=>ArtifactUnlockedPayload(decoded['artifact_id'] as String),_=>throw UnsupportedStoryEventType(eventType)}; } }
final class UnsupportedStoryPayloadVersion implements Exception { final String eventType; final int version; const UnsupportedStoryPayloadVersion(this.eventType,this.version); @override String toString()=>'Unsupported payload version $version for $eventType'; }
final class UnsupportedStoryEventType implements Exception { final String eventType; const UnsupportedStoryEventType(this.eventType); @override String toString()=>'Unsupported story event type $eventType'; }
