import '../../domain/release/release_models.dart';

abstract final class GoldenJourneyCatalog {
  static const List<GoldenJourneyDefinition> mandatory = [
    GoldenJourneyDefinition(id: 'GJ-01', title: 'Standard Speech Journey', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-02', title: 'Speech-Free Journey', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-03', title: 'Speech Uncertainty', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-04', title: 'Speech Technical Failure', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-05', title: 'Semantic Failure', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-06', title: 'Full Help Path', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-07', title: 'Listening Audio Path', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-08', title: 'Listening Accessibility Alternative', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-09', title: 'App Kill Before Commit', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-10', title: 'App Kill After Commit', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-11', title: 'Double Submit', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-12', title: 'Stale Async Speech Result', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-13', title: 'Character Memory Persistence', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-14', title: 'Character Knowledge Isolation', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-15', title: 'Character Leak Validation', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-16', title: 'Story Projection Rebuild', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-17', title: 'Language Book Rebuild', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-18', title: 'Passport Rebuild', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-19', title: 'Artifact Snapshot Immutability', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-20', title: 'Artifact Speech Claim', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-21', title: 'Artifact Text Claim', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-22', title: 'Artifact Full-Model Claim', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-23', title: 'Offline Cold Start', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-24', title: 'Offline Stage Completion', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-25', title: 'Offline + Speech Unavailable', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-26', title: 'Wi-Fi Only', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-27', title: 'Mobile Data Allowed', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-28', title: 'Network Switch During Download', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-29', title: 'Corrupt Package', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-30', title: 'Broken New Version', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-31', title: 'Package Removal', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-32', title: 'Reinstall & Resume', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-33', title: 'Large Text', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-34', title: 'Reduced Motion', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-35', title: 'TalkBack', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-36', title: 'VoiceOver', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-37', title: 'Screenreader + Speech-Free', executionMode: GoldenJourneyExecutionMode.manualRealDevice),
    GoldenJourneyDefinition(id: 'GJ-38', title: 'Logging Privacy', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-39', title: 'Temporary Audio Cleanup', executionMode: GoldenJourneyExecutionMode.semiAutomated),
    GoldenJourneyDefinition(id: 'GJ-40', title: 'Content Change Without Flutter Code', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-41', title: 'Branch Change Without Flutter Code', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-42', title: 'Wrong Evidence Mapping', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-43', title: 'OPEN_NAME Invalid Evidence', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-44', title: 'Database Migration', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-45', title: 'Profile Isolation', executionMode: GoldenJourneyExecutionMode.automated),
    GoldenJourneyDefinition(id: 'GJ-46', title: 'Language Isolation', executionMode: GoldenJourneyExecutionMode.automated),
  ];
}
