import 'package:flutter/material.dart';

class JourneyIntroFlow extends StatefulWidget {
  final String language, flag, greeting, backgroundAsset, guideKey, guideName;
  const JourneyIntroFlow({super.key,required this.language,required this.flag,required this.greeting,required this.backgroundAsset,required this.guideKey,required this.guideName});
  @override State<JourneyIntroFlow> createState()=>_JourneyIntroFlowState();
}

class _JourneyIntroFlowState extends State<JourneyIntroFlow>{
  int _step=1; String? _selectedLevel; final Set<String> _selectedGoals={}; final Set<String> _selectedLearningStyles={}; final _nameController=TextEditingController();
  bool get _isLeon=>widget.guideKey=='leon';
  String get learningGreeting=>widget.language=='Türkçe'?'Merhaba!':widget.language=='Ελληνικά'?'Γεια σου!':'Hello!';
  String get _activeBackground{if(_step<3)return widget.backgroundAsset;if(widget.language=='Türkçe')return 'assets/backgrounds/onboarding_3_turkish.png';if(widget.language=='Ελληνικά')return 'assets/backgrounds/onboarding_3_greek.png';return 'assets/backgrounds/onboarding_3_english.png';}
  String get _guideAsset{switch(_step){case 2:return _isLeon?'assets/characters/leon_confident.png':'assets/characters/maria_confident.png';case 3:return _isLeon?'assets/characters/leon_relaxed.png':'assets/characters/maria_thinking.png';case 4:return _isLeon?'assets/characters/leon_invite.png':'assets/characters/maria_welcome.png';case 5:return _isLeon?'assets/characters/leon_thumbsup.png':'assets/characters/maria_pointing.png';default:return _isLeon?'assets/characters/leon_invite.png':'assets/characters/maria_welcome.png';}}
  @override void dispose(){_nameController.dispose();super.dispose();}
  @override Widget build(BuildContext context){final s=MediaQuery.sizeOf(context),l=s.width>s.height;return Scaffold(resizeToAvoidBottomInset:true,backgroundColor:const Color(0xFF050508),body:Stack(fit:StackFit.expand,children:[Positioned.fill(child:Image.asset(_activeBackground,fit:BoxFit.cover,alignment:Alignment.center,errorBuilder:(_,__,___)=>const ColoredBox(color:Color(0xFF050508)))),const Positioned.fill(child:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0x10000000),Color(0x05000000),Color(0xA8000000)],stops:[0,.55,1])))),_guideLayer(s,l),SafeArea(child:Padding(padding:EdgeInsets.fromLTRB(l?24:18,l?8:12,l?24:18,l?10:18),child:_buildStep(s,l)))]));}
  Widget _buildStep(Size s,bool l){switch(_step){case 1:return _page(s,l,_welcomeCard(l?s.width*.56:s.width*.68,l),()=>Navigator.pop(context),()=>setState(()=>_step=2),right:true);case 2:return _page(s,l,_nameCard(l?s.width*.62:s.width*.66,l),()=>setState(()=>_step=1),_nameController.text.trim().isEmpty?null:(){FocusScope.of(context).unfocus();setState(()=>_step=3);});case 3:return _page(s,l,_levelCard(l?s.width*.57:s.width*.72,l),()=>setState(()=>_step=2),_selectedLevel==null?null:()=>setState(()=>_step=4),right:true);case 4:return _page(s,l,_goalsCard(l?s.width*.60:s.width*.72,l),()=>setState(()=>_step=3),_selectedGoals.isEmpty?null:()=>setState(()=>_step=5),right:l?false:true);default:return _page(s,l,_learningCard(l?s.width*.60:s.width*.72,l),()=>setState(()=>_step=4),_selectedLearningStyles.isEmpty?null:(){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Schritt 6 folgt als Nächstes.')));},right:true);}}
  Widget _page(Size s,bool l,Widget card,VoidCallback back,VoidCallback? next,{bool right=false})=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_header(back),const Spacer(),Align(alignment:right?Alignment.centerRight:Alignment.centerLeft,child:card),SizedBox(height:l?7:12),Align(alignment:right?Alignment.centerRight:Alignment.centerLeft,child:SizedBox(width:l?s.width*.44:double.infinity,child:_pinkButton('Weiter',next,height:l?46:58)))]);
  Widget _guideLayer(Size s,bool l){final right=_step==2;if(l)return Positioned(left:right?null:-12,right:right?-8:null,bottom:-10,child:IgnorePointer(child:SizedBox(width:s.width*(_step>=3?.27:.32),height:s.height*.88,child:Image.asset(_guideAsset,fit:BoxFit.contain,alignment:right?Alignment.bottomRight:Alignment.bottomLeft,errorBuilder:(_,__,___)=>const SizedBox.shrink()))));if(_step==4||_step==5)return Positioned(left:-52,bottom:92,child:IgnorePointer(child:SizedBox(width:s.width*.52,height:s.height*.48,child:Image.asset(_guideAsset,fit:BoxFit.contain,alignment:Alignment.bottomLeft,errorBuilder:(_,__,___)=>const SizedBox.shrink()))));return Positioned(left:right?null:-28,right:right?-32:null,bottom:_step>=3?105:120,child:IgnorePointer(child:SizedBox(width:s.width*(_step>=3?.43:.62),height:s.height*(_step>=3?.43:.58),child:Image.asset(_guideAsset,fit:BoxFit.contain,alignment:right?Alignment.bottomRight:Alignment.bottomLeft,errorBuilder:(_,__,___)=>const SizedBox.shrink()))));}
  Widget _welcomeCard(double w,bool c)=>Container(width:w,padding:EdgeInsets.all(c?16:18),decoration:_dec(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[Row(children:[const Icon(Icons.favorite_rounded,color:Color(0xFFFF2E9A),size:21),const SizedBox(width:8),Text(learningGreeting,style:TextStyle(color:const Color(0xFFFF5BAE),fontSize:c?15:17,fontWeight:FontWeight.w800))]),SizedBox(height:c?6:10),Text('${widget.guideName} begrüßt dich',style:TextStyle(color:Colors.white,fontSize:c?24:28,fontWeight:FontWeight.w900)),SizedBox(height:c?6:10),const Divider(color:Color(0xCCFF2E9A)),SizedBox(height:c?6:10),Text('Schön, dass du da bist. Bevor wir gemeinsam auf Reisen gehen, möchte ich dich ein wenig kennenlernen.',style:TextStyle(color:const Color(0xFFF2EDF2),fontSize:c?12.5:14.5,height:1.35)),SizedBox(height:c?8:12),Text('${widget.flag} ${widget.language}',style:TextStyle(color:const Color(0xFFFF5BAE),fontSize:c?16:18,fontWeight:FontWeight.w900))]));
  Widget _nameCard(double w,bool c)=>Container(width:w,padding:EdgeInsets.all(c?14:18),decoration:_dec(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[_eyebrow('LERNEN WIR UNS KENNEN',c),const SizedBox(height:7),_title('Wie darf ich dich nennen?',c),const SizedBox(height:7),Text('Dein Name macht deine Reise persönlicher. ${widget.guideName} wird dich während des Lernens damit ansprechen.',style:TextStyle(color:const Color(0xFFF2EDF2),fontSize:c?12:13.5)),SizedBox(height:c?9:13),TextField(controller:_nameController,onChanged:(_)=>setState((){}),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700),decoration:InputDecoration(hintText:'Dein Vorname',hintStyle:const TextStyle(color:Color(0xFFAAA3AC)),prefixIcon:const Icon(Icons.person_outline_rounded,color:Color(0xFFFF2E9A)),filled:true,fillColor:const Color(0xE61E1C22),border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)))),SizedBox(height:c?8:11),Text('${widget.flag}  Du lernst ${widget.language} – Schritt für Schritt und in deinem Tempo.',style:TextStyle(color:Colors.white,fontSize:c?11.5:12.5,fontWeight:FontWeight.w600))]));
  Widget _levelCard(double w,bool c)=>_selection(w,c,'DEIN STARTPUNKT','Wo stehst du gerade?','${widget.guideName} passt deine ersten Schritte an dein aktuelles Niveau an.',[_single('new',Icons.auto_awesome_rounded,'Ich starte ganz neu','Keine oder fast keine Vorkenntnisse',c),_single('words',Icons.chat_bubble_outline_rounded,'Ich kenne ein paar Wörter','Begrüßungen und einzelne Begriffe',c),_single('sentences',Icons.record_voice_over_rounded,'Ich kann einfache Sätze','Kurze Alltagssituationen klappen schon',c),_single('restart',Icons.refresh_rounded,'Ich möchte wieder einsteigen','Früher gelernt – jetzt auffrischen',c)]);
  Widget _goalsCard(double w,bool c)=>_selection(w,c,'DEINE REISE','Was möchtest du mit der Sprache erleben?','Wähle alles aus, was zu dir passt. ${widget.guideName} richtet deine Reise danach aus.',[_multi(_selectedGoals,'travel',Icons.flight_takeoff_rounded,'Auf Reisen','Im Urlaub sicherer sprechen',c),_multi(_selectedGoals,'everyday',Icons.forum_outlined,'Im Alltag','Gespräche verstehen und führen',c),_multi(_selectedGoals,'culture',Icons.favorite_outline_rounded,'Menschen & Kultur','Sprache und Kultur wirklich erleben',c),_multi(_selectedGoals,'myself',Icons.explore_outlined,'Für mich selbst','Einfach eine neue Sprache lernen',c)]);
  Widget _learningCard(double w,bool c)=>_selection(w,c,'DEIN LERNWEG','Wie lernst du am liebsten?','Wähle aus, was dir beim Lernen besonders hilft. ${widget.guideName} passt deine Reise daran an.',[_multi(_selectedLearningStyles,'listen',Icons.headphones_rounded,'Hören & Nachsprechen','Aussprache hören und direkt üben',c),_multi(_selectedLearningStyles,'visual',Icons.visibility_outlined,'Sehen & Entdecken','Mit Bildern und Situationen lernen',c),_multi(_selectedLearningStyles,'write',Icons.edit_outlined,'Lesen & Schreiben','Wörter und Sätze selbst anwenden',c),_multi(_selectedLearningStyles,'speak',Icons.record_voice_over_rounded,'Sprechen & Erleben','In echten Alltagssituationen üben',c)]);
  Widget _selection(double w,bool c,String e,String t,String sub,List<Widget> items)=>Container(width:w,padding:EdgeInsets.all(c?12:14),decoration:_dec(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[_eyebrow(e,c),SizedBox(height:c?3:5),_title(t,c),SizedBox(height:c?3:5),Text(sub,style:TextStyle(color:const Color(0xFFF2EDF2),fontSize:c?10.5:11.5,height:1.2)),SizedBox(height:c?7:9),Row(children:[Expanded(child:items[0]),const SizedBox(width:7),Expanded(child:items[1])]),const SizedBox(height:7),Row(children:[Expanded(child:items[2]),const SizedBox(width:7),Expanded(child:items[3])]) ]));
  Widget _single(String v,IconData i,String t,String s,bool c)=>_choice(i,t,s,_selectedLevel==v,()=>setState(()=>_selectedLevel=v),c);
  Widget _multi(Set<String> set,String v,IconData i,String t,String s,bool c)=>_choice(i,t,s,set.contains(v),()=>setState(()=>set.contains(v)?set.remove(v):set.add(v)),c);
  Widget _choice(IconData i,String t,String s,bool selected,VoidCallback tap,bool c)=>Material(color:Colors.transparent,child:InkWell(onTap:tap,borderRadius:BorderRadius.circular(14),child:AnimatedContainer(duration:const Duration(milliseconds:180),constraints:BoxConstraints(minHeight:c?64:78),padding:EdgeInsets.symmetric(horizontal:c?7:9,vertical:c?6:8),decoration:BoxDecoration(color:selected?const Color(0x3DFF2E9A):const Color(0xC91E1C22),borderRadius:BorderRadius.circular(14),border:Border.all(color:selected?const Color(0xFFFF2E9A):const Color(0xFF3C3740),width:selected?1.7:1)),child:Row(children:[Icon(i,color:const Color(0xFFFF2E9A),size:c?18:20),const SizedBox(width:7),Expanded(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,maxLines:2,style:TextStyle(color:Colors.white,fontSize:c?10.5:11.5,fontWeight:FontWeight.w800)),const SizedBox(height:2),Text(s,maxLines:c?2:3,style:TextStyle(color:const Color(0xFFD7D0D7),fontSize:c?8.5:9.3))])),if(selected)const Icon(Icons.check_circle_rounded,color:Color(0xFFFF2E9A),size:17)]))));
  Widget _header(VoidCallback back)=>Align(alignment:Alignment.centerLeft,child:IconButton(onPressed:back,icon:const Icon(Icons.arrow_back_rounded,color:Colors.white,size:34)));
  Widget _eyebrow(String x,bool c)=>Text(x,style:TextStyle(color:const Color(0xFFFF5BAE),fontSize:c?11:12.5,fontWeight:FontWeight.w900));
  Widget _title(String x,bool c)=>Text(x,style:TextStyle(color:Colors.white,fontSize:c?19:22,fontWeight:FontWeight.w900));
  BoxDecoration _dec()=>BoxDecoration(color:const Color(0xE817161A),borderRadius:BorderRadius.circular(26),border:Border.all(color:const Color(0x44FFFFFF)),boxShadow:const[BoxShadow(color:Color(0x77000000),blurRadius:28,offset:Offset(0,12))]);
  Widget _pinkButton(String label,VoidCallback? tap,{double height=62})=>SizedBox(width:double.infinity,height:height,child:FilledButton(onPressed:tap,style:FilledButton.styleFrom(backgroundColor:const Color(0xFFFF2E9A),disabledBackgroundColor:const Color(0x88FF2E9A),foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(height/2))),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text(label,style:TextStyle(fontSize:height<55?18:20,fontWeight:FontWeight.w900)),const SizedBox(width:12),Icon(Icons.arrow_forward_rounded,size:height<55?24:28)])));
}
