import 'package:flutter/material.dart';

class JourneyDashboardScreen extends StatelessWidget {
  final String name;
  final String language;
  final String flag;
  final String guideName;
  final String guideKey;
  final String backgroundAsset;

  const JourneyDashboardScreen({super.key,required this.name,required this.language,required this.flag,required this.guideName,required this.guideKey,required this.backgroundAsset});

  String get _chapterBackground {if(language=='Türkçe')return 'assets/backgrounds/gate_turkish.jpg';if(language=='Ελληνικά')return 'assets/backgrounds/gate_greek.jpg';return 'assets/backgrounds/gate_english.jpg';}
  String get _chapterTitle {if(language=='Türkçe')return 'Ankommen & Begrüßen';if(language=='Ελληνικά')return 'Άφιξη & Χαιρετισμοί';return 'Arriving & Greetings';}

  @override Widget build(BuildContext context){final s=MediaQuery.sizeOf(context),l=s.width>s.height;return Scaffold(backgroundColor:const Color(0xFF050508),body:Stack(fit:StackFit.expand,children:[Image.asset(_chapterBackground,fit:BoxFit.cover,alignment:Alignment.center,filterQuality:FilterQuality.high,errorBuilder:(_,__,___)=>Image.asset(backgroundAsset,fit:BoxFit.cover,alignment:Alignment.center)),const DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0x10000000),Color(0x05000000),Color(0xA8000000)],stops:[0,.55,1]))),SafeArea(child:Padding(padding:EdgeInsets.fromLTRB(l?24:18,l?8:12,l?24:18,l?10:18),child:l?_landscape(context,s):_portrait(context,s)))]));}

  Widget _portrait(BuildContext context,Size s)=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_header(),const Spacer(),Align(alignment:Alignment.centerRight,child:SizedBox(width:s.width*.72,child:_chapterCard(context,false))),const SizedBox(height:12),_quickAccess(false)]);
  Widget _landscape(BuildContext context,Size s)=>Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_header(),const Spacer(),Align(alignment:Alignment.centerRight,child:SizedBox(width:s.width*.60,child:_chapterCard(context,true))),const SizedBox(height:7),Align(alignment:Alignment.centerRight,child:SizedBox(width:s.width*.60,child:_quickAccess(true)))]);

  Widget _header()=>Row(children:[const Icon(Icons.travel_explore_rounded,color:Colors.white,size:30),const SizedBox(width:8),const Expanded(child:Text('Reise mit Worten',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900))),Text('$flag  $language',style:const TextStyle(color:Colors.white,fontSize:14,fontWeight:FontWeight.w800))]);

  BoxDecoration _onboardingDecoration({double radius=26})=>BoxDecoration(color:const Color(0xE817161A),borderRadius:BorderRadius.circular(radius),border:Border.all(color:const Color(0x664A444D)),boxShadow:const [BoxShadow(color:Color(0x66000000),blurRadius:24,offset:Offset(0,10))]);

  Widget _chapterCard(BuildContext context,bool compact)=>Container(padding:EdgeInsets.all(compact?15:18),decoration:_onboardingDecoration(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[Text('DEINE REISE',style:TextStyle(color:const Color(0xFFFF5BAE),fontSize:compact?11:12,fontWeight:FontWeight.w900)),SizedBox(height:compact?4:6),Text('Willkommen, $name!',style:TextStyle(color:Colors.white,fontSize:compact?24:28,fontWeight:FontWeight.w900)),SizedBox(height:compact?4:7),Text('$guideName begleitet dich. Heute beginnt dein erstes Kapitel.',style:TextStyle(color:const Color(0xFFF2EDF2),fontSize:compact?11.5:13,height:1.3)),SizedBox(height:compact?9:12),const Divider(color:Color(0xCCFF2E9A),height:1),SizedBox(height:compact?9:12),Row(children:[const Icon(Icons.waving_hand_rounded,color:Color(0xFFFF2E9A),size:24),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Kapitel 1',style:TextStyle(color:Color(0xFFFF5BAE),fontWeight:FontWeight.w900)),Text(_chapterTitle,style:TextStyle(color:Colors.white,fontSize:compact?17:19,fontWeight:FontWeight.w900))]))]),SizedBox(height:compact?9:11),ClipRRect(borderRadius:BorderRadius.circular(20),child:const LinearProgressIndicator(value:0,minHeight:7,backgroundColor:Color(0xFF3B373E),valueColor:AlwaysStoppedAnimation(Color(0xFFFF2E9A)))),const SizedBox(height:5),const Text('0 % abgeschlossen',style:TextStyle(color:Color(0xFFD8D0D7),fontSize:10.5)),SizedBox(height:compact?9:12),SizedBox(width:double.infinity,height:compact?46:54,child:FilledButton(onPressed:(){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Kapitel 1 wird als Nächstes aufgebaut.')));},style:FilledButton.styleFrom(backgroundColor:const Color(0xFFFF2E9A),foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(28))),child:const Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text('Reise starten',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),SizedBox(width:10),Icon(Icons.arrow_forward_rounded)]))) ]));

  Widget _quickAccess(bool compact){const items=<({IconData icon,String label})>[(icon:Icons.public_rounded,label:'Reisepass'),(icon:Icons.menu_book_rounded,label:'Sprachbuch'),(icon:Icons.folder_copy_outlined,label:'Sprachordner')];return Row(children:[for(var i=0;i<items.length;i++)...[Expanded(child:Container(height:compact?54:66,decoration:_onboardingDecoration(radius:18),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(items[i].icon,color:const Color(0xFFFF5BAE),size:compact?20:23),const SizedBox(height:3),FittedBox(fit:BoxFit.scaleDown,child:Text(items[i].label,style:TextStyle(color:Colors.white,fontSize:compact?9.5:10.5,fontWeight:FontWeight.w800)))]))),if(i!=items.length-1)const SizedBox(width:7)]]);}
}
